# Taskfile.yml
version: '3'

tasks:
  generate:
    cmd: go run .

  generate:clean:
    cmd: go run generate.go -clean

  ruby:
    dir: ruby
    cmd: go run .

  all:
    deps: [ruby]
    cmd: go run generate.go