# Taskfile.yml
version: '3'

tasks:
  generate:
    cmd: go run generate.go

  generate:clean:
    cmd: go run generate.go -clean

  ruby:
    dir: ruby
    cmds:
      - git -C .. pull
      - go run . {{.CLI_ARGS}}

  all:
    deps: [ruby]
    cmd: go run generate.go

  push:
    desc: build check then push
    cmds:
      - go vet ./...
      - cd ruby && go vet ./...
      - git push {{.CLI_ARGS}}